version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  # Use the default service rule to route to the /admin context path
  admin:
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      # PIEHOLE_PTR: whaletown-pi
      FTLCONF_LOCAL_IPV4: 192.168.1.4
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq_d:/etc/dnsmasq.d'
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=local
      - traefik.http.services.piehole.loadbalancer.server.port=80
    networks:
      local:
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

volumes:
  etc-pihole:
  etc-dnsmasq_d:

networks:
  local:
    external: true
