version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  # Use the default service rule to route to the /admin context path
  pihole:
    image: pihole/pihole:2025.04.0
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'America/Los_Angeles'
      FTLCONF_dns_reply_host_force4: "true"
      FTLCONF_dns_reply_host_IPv4: ${FTLCONF_dns_reply_host_IPv4}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${WEBSERVER_PASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole:/etc/pihole'
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=local
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.rule=Host(`pi.hole`)
    networks:
      - local
    dns:
      - 127.0.0.1
      - 1.1.1.1

volumes:
  etc-pihole:

networks:
  #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  # cap_add:
  #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
  local:
    external: true
